### ISSUE TITLE
Guide of setting item is necessary.

### ISSUE THREAD

**Issue by kanink007** [f11894/waifu2x-chainer-GUI#5]
EDIT: i solved the problem. it works with python 3.6
before, i was using python 2.7.

but.. if no one minds, i would like to ask a question here: can you make some kind a "guide" or "how to" and explain, what all options are good for?
like.. what is block size, batch size, vgg7, upconv7, resnet10, tta ad tta level etc.

maybe the answers are obvious for people who have deeper knowledge about graphics, editing etc.. but i would like to use chainer with the gui properly, so if you dont mind explaining me.. i would be happy.

greetings

**Comment by f11894** [comment]
### block size
   Processing large images at the same time results in insufficient memory, so it needs to be divided into small pieces and processed.
   This is the size you want to divide.
   If you specify a large value, memory consumption will increase but processing speed will be slightly faster.

### batch size
   I do not know well about this, so please ask the author of waifu2x-chainer if you want to know more.

### vgg7 upconv7 resnet10
   The type of deep learning architecture.
   Since vgg 7 and upconv 7 can also be used in waifu 2 x - caffe, we usually recommend using resnet 10 which can only be used with waifu 2 x - chainer.
   The performance of resnet 10 is the highest.

### tta tta level
   Enabling this will slightly increase the image quality.
   The larger the value of tta level, the higher the image quality, but the processing time increases.
   If tta level 8, the processing time will be 8 times.



### block size
   大きな画像を一度に処理するとメモリが足りなくなるので小さく分割して処理する必要があります。
   その際に指定する分割するサイズです。
   大きな値を指定するとメモリの消費量が増えますが処理速度が少しだけ早くなります。

### batch size
   これに関しては私はよく分からないので詳しく知りたい場合はwaifu2x-chainerの作者に聞いてください。

### vgg7 upconv7 resnet10
   ディープラーニングのアーキテクチャの種類です。
   vgg7とupconv7はwaifu2x-caffeでも利用できるので、通常はwaifu2x-chainerでしか利用できないresnet10を利用するのをお勧めします。
   resnet10の性能が最も高いです。

### tta tta level
   これを有効にすると画質が少しだけ上がります。
   tta levelの値が大きいほど画質が上がりますが、処理時間は増えます。
   tta level8だと処理時間は8倍になります。
